[2024-06-28T09:03:57.921+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T09:03:57.960+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_sample_dag.task_from_script1 manual__2024-06-28T00:04:14.339358+00:00 [queued]>
[2024-06-28T09:03:57.973+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_sample_dag.task_from_script1 manual__2024-06-28T00:04:14.339358+00:00 [queued]>
[2024-06-28T09:03:57.974+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-06-28T09:03:57.994+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task_from_script1> on 2024-06-28 00:04:14.339358+00:00
[2024-06-28T09:03:58.003+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=468) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T09:03:58.006+0000] {standard_task_runner.py:63} INFO - Started process 485 to run task
[2024-06-28T09:03:58.006+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_sample_dag', 'task_from_script1', 'manual__2024-06-28T00:04:14.339358+00:00', '--job-id', '739', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmprsvwl2el']
[2024-06-28T09:03:58.009+0000] {standard_task_runner.py:91} INFO - Job 739: Subtask task_from_script1
[2024-06-28T09:03:58.074+0000] {task_command.py:426} INFO - Running <TaskInstance: my_sample_dag.task_from_script1 manual__2024-06-28T00:04:14.339358+00:00 [running]> on host 1d2e3c34485f
[2024-06-28T09:03:58.202+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_sample_dag' AIRFLOW_CTX_TASK_ID='task_from_script1' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T00:04:14.339358+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T00:04:14.339358+00:00'
[2024-06-28T09:03:58.204+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T09:03:58.573+0000] {logging_mixin.py:188} INFO - Donn√©es API ok..
[2024-06-28T09:03:58.652+0000] {logging_mixin.py:188} INFO - Sauvegarde ok ..
[2024-06-28T09:03:58.658+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T09:03:58.660+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T09:03:58.673+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_sample_dag, task_id=task_from_script1, run_id=manual__2024-06-28T00:04:14.339358+00:00, execution_date=20240628T000414, start_date=20240628T090357, end_date=20240628T090358
[2024-06-28T09:03:58.723+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T09:03:58.765+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-28T09:03:58.768+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
