[2024-06-28T08:57:41.499+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T08:57:41.505+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T08:57:41.515+0000] {logging_mixin.py:188} INFO - [2024-06-28T08:57:41.513+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T08:57:45.655+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T08:57:47.212+0000] {logging_mixin.py:188} INFO - [2024-06-28T08:57:47.206+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T08:57:47.222+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T08:57:47.497+0000] {logging_mixin.py:188} INFO - [2024-06-28T08:57:47.497+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T08:57:47.544+0000] {logging_mixin.py:188} INFO - [2024-06-28T08:57:47.544+0000] {dag.py:3954} INFO - Setting next_dagrun for my_sample_dag to 2024-01-05 00:00:00+00:00, run_after=2024-01-05 00:05:00+00:00
[2024-06-28T08:57:47.593+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 6.121 seconds
[2024-06-28T08:58:17.763+0000] {processor.py:161} INFO - Started process (PID=126) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T08:58:17.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T08:58:17.768+0000] {logging_mixin.py:188} INFO - [2024-06-28T08:58:17.767+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T08:58:18.275+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T08:58:18.928+0000] {logging_mixin.py:188} INFO - [2024-06-28T08:58:18.926+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T08:58:18.929+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T08:58:18.951+0000] {logging_mixin.py:188} INFO - [2024-06-28T08:58:18.951+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T08:58:18.997+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.241 seconds
[2024-06-28T08:58:49.422+0000] {processor.py:161} INFO - Started process (PID=195) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T08:58:49.423+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T08:58:49.427+0000] {logging_mixin.py:188} INFO - [2024-06-28T08:58:49.426+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T08:58:49.969+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T08:58:50.623+0000] {logging_mixin.py:188} INFO - [2024-06-28T08:58:50.621+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T08:58:50.625+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T08:58:50.645+0000] {logging_mixin.py:188} INFO - [2024-06-28T08:58:50.645+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T08:58:50.690+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.277 seconds
[2024-06-28T08:59:21.210+0000] {processor.py:161} INFO - Started process (PID=267) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T08:59:21.212+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T08:59:21.215+0000] {logging_mixin.py:188} INFO - [2024-06-28T08:59:21.214+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T08:59:21.844+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T08:59:22.571+0000] {logging_mixin.py:188} INFO - [2024-06-28T08:59:22.569+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T08:59:22.572+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T08:59:22.598+0000] {logging_mixin.py:188} INFO - [2024-06-28T08:59:22.597+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T08:59:22.657+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.455 seconds
[2024-06-28T08:59:52.764+0000] {processor.py:161} INFO - Started process (PID=337) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T08:59:52.767+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T08:59:52.770+0000] {logging_mixin.py:188} INFO - [2024-06-28T08:59:52.769+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T08:59:53.387+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T08:59:54.532+0000] {logging_mixin.py:188} INFO - [2024-06-28T08:59:54.529+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T08:59:54.534+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T08:59:54.594+0000] {logging_mixin.py:188} INFO - [2024-06-28T08:59:54.594+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T08:59:54.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.905 seconds
[2024-06-28T09:00:24.820+0000] {processor.py:161} INFO - Started process (PID=409) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:00:24.821+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:00:24.824+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:00:24.823+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:00:25.345+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:00:26.102+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:00:26.101+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:00:26.103+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:00:26.126+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:00:26.126+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:00:26.177+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.365 seconds
[2024-06-28T09:00:56.321+0000] {processor.py:161} INFO - Started process (PID=477) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:00:56.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:00:56.326+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:00:56.325+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:00:56.916+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:00:57.621+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:00:57.619+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:00:57.622+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:00:57.647+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:00:57.647+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:00:57.706+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.394 seconds
[2024-06-28T09:01:28.192+0000] {processor.py:161} INFO - Started process (PID=549) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:01:28.193+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:01:28.197+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:01:28.196+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:01:28.872+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:01:29.866+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:01:29.864+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:01:29.867+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:01:29.893+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:01:29.893+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:01:29.955+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.772 seconds
[2024-06-28T09:02:00.674+0000] {processor.py:161} INFO - Started process (PID=620) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:02:00.675+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:02:00.678+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:02:00.677+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:02:01.176+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:02:01.803+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:02:01.802+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:02:01.804+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:02:01.826+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:02:01.826+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:02:01.875+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.209 seconds
[2024-06-28T09:02:32.027+0000] {processor.py:161} INFO - Started process (PID=689) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:02:32.028+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:02:32.031+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:02:32.030+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:02:32.546+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:02:33.253+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:02:33.251+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:02:33.254+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:02:33.277+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:02:33.277+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:02:33.324+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.306 seconds
[2024-06-28T09:03:03.857+0000] {processor.py:161} INFO - Started process (PID=762) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:03:03.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:03:03.862+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:03:03.862+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:03:04.361+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:03:05.039+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:03:05.038+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:03:05.041+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:03:05.065+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:03:05.064+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:03:05.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.270 seconds
[2024-06-28T09:03:33.990+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:03:33.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:03:33.996+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:03:33.995+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:03:34.848+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:03:36.870+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:03:36.868+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:03:36.897+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:03:37.116+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:03:37.115+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:03:37.337+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 3.353 seconds
[2024-06-28T09:04:07.863+0000] {processor.py:161} INFO - Started process (PID=114) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:04:07.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:04:07.870+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:04:07.870+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:04:08.653+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:04:09.480+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:04:09.477+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:04:09.481+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:04:09.505+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:04:09.505+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:04:09.554+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.702 seconds
[2024-06-28T09:04:39.667+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:04:39.668+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:04:39.671+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:04:39.671+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:04:40.267+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:04:41.038+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:04:41.037+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:04:41.040+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:04:41.064+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:04:41.063+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:04:41.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.461 seconds
[2024-06-28T09:05:11.284+0000] {processor.py:161} INFO - Started process (PID=257) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:05:11.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:05:11.291+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:05:11.290+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:05:11.951+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:05:12.692+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:05:12.690+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:05:12.693+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:05:12.714+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:05:12.714+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:05:12.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.488 seconds
[2024-06-28T09:05:43.072+0000] {processor.py:161} INFO - Started process (PID=329) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:05:43.074+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:05:43.078+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:05:43.077+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:05:43.676+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:05:44.481+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:05:44.480+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:05:44.482+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:05:44.504+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:05:44.504+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:05:44.550+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.486 seconds
[2024-06-28T09:06:14.628+0000] {processor.py:161} INFO - Started process (PID=401) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:06:14.629+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:06:14.632+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:06:14.632+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:06:15.216+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:06:16.259+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:06:16.258+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:06:16.260+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:06:16.290+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:06:16.290+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:06:16.373+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.754 seconds
[2024-06-28T09:06:46.521+0000] {processor.py:161} INFO - Started process (PID=473) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:06:46.523+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:06:46.526+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:06:46.525+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:06:47.058+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:06:47.782+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:06:47.781+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:06:47.783+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:06:47.815+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:06:47.814+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:06:47.909+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.396 seconds
[2024-06-28T09:07:18.696+0000] {processor.py:161} INFO - Started process (PID=541) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:07:18.698+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:07:18.701+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:07:18.700+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:07:19.239+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:07:19.987+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:07:19.986+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:07:19.989+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:07:20.011+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:07:20.011+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:07:20.058+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.371 seconds
[2024-06-28T09:07:51.056+0000] {processor.py:161} INFO - Started process (PID=616) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:07:51.058+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:07:51.062+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:07:51.061+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:07:51.615+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:07:52.368+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:07:52.367+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:07:52.369+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:07:52.392+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:07:52.392+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:07:52.453+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.407 seconds
[2024-06-28T09:08:22.514+0000] {processor.py:161} INFO - Started process (PID=684) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:08:22.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:08:22.521+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:08:22.520+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:08:23.106+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:08:23.960+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:08:23.959+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:08:23.961+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:08:23.990+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:08:23.990+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:08:24.066+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.560 seconds
[2024-06-28T09:08:55.653+0000] {processor.py:161} INFO - Started process (PID=777) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:08:55.658+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:08:55.672+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:08:55.670+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:08:57.513+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:09:00.507+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:09:00.505+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:09:00.512+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:09:00.565+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:09:00.558+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:09:00.765+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 5.126 seconds
[2024-06-28T09:09:31.285+0000] {processor.py:161} INFO - Started process (PID=875) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:09:31.288+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:09:31.295+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:09:31.294+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:09:32.842+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:09:34.010+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:09:34.008+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:09:34.012+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:09:34.042+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:09:34.041+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:09:34.100+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 2.837 seconds
[2024-06-28T09:10:04.153+0000] {processor.py:161} INFO - Started process (PID=951) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T09:10:04.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T09:10:04.158+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:10:04.157+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T09:10:04.772+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T09:10:05.617+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:10:05.615+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:10:05.618+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T09:10:05.641+0000] {logging_mixin.py:188} INFO - [2024-06-28T09:10:05.641+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T09:10:05.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.541 seconds
[2024-06-28T13:44:55.137+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:44:55.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:44:55.147+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:44:55.146+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:44:58.642+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:45:01.046+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:45:01.044+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:45:01.052+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:45:01.298+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:45:01.298+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:45:01.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 6.277 seconds
[2024-06-28T13:45:32.262+0000] {processor.py:161} INFO - Started process (PID=115) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:45:32.264+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:45:32.267+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:45:32.266+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:45:32.895+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:45:33.712+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:45:33.710+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:45:33.714+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:45:33.743+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:45:33.743+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:45:33.800+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.547 seconds
[2024-06-28T13:46:04.097+0000] {processor.py:161} INFO - Started process (PID=190) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:46:04.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:46:04.107+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:46:04.106+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:46:04.764+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:46:05.495+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:46:05.494+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:46:05.496+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:46:05.522+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:46:05.522+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:46:05.573+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.489 seconds
[2024-06-28T13:46:36.211+0000] {processor.py:161} INFO - Started process (PID=263) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:46:36.214+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:46:36.217+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:46:36.217+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:46:36.800+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:46:37.572+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:46:37.571+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:46:37.573+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:46:37.597+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:46:37.597+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:46:37.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.444 seconds
[2024-06-28T13:47:08.694+0000] {processor.py:161} INFO - Started process (PID=362) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:47:08.701+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:47:08.733+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:47:08.732+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:47:10.793+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:47:12.948+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:47:12.946+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:47:12.951+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:47:13.000+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:47:13.000+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:47:13.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 4.469 seconds
[2024-06-28T13:47:43.203+0000] {processor.py:161} INFO - Started process (PID=435) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:47:43.205+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:47:43.208+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:47:43.208+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:47:43.864+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:47:44.638+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:47:44.637+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:47:44.640+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:47:44.662+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:47:44.661+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:47:44.711+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.518 seconds
[2024-06-28T13:48:15.250+0000] {processor.py:161} INFO - Started process (PID=509) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:48:15.252+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:48:15.256+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:48:15.255+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:48:15.864+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:48:16.578+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:48:16.576+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:48:16.578+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:48:16.603+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:48:16.603+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:48:16.657+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.414 seconds
[2024-06-28T13:48:46.836+0000] {processor.py:161} INFO - Started process (PID=581) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:48:46.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:48:46.843+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:48:46.842+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:48:47.623+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:48:48.386+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:48:48.384+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:48:48.387+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:48:48.411+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:48:48.411+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:48:48.482+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.657 seconds
[2024-06-28T13:49:18.561+0000] {processor.py:161} INFO - Started process (PID=654) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:49:18.563+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:49:18.566+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:49:18.566+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:49:19.128+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:49:19.939+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:49:19.938+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:49:19.940+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:49:19.962+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:49:19.962+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:49:20.011+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.458 seconds
[2024-06-28T13:49:50.133+0000] {processor.py:161} INFO - Started process (PID=726) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:49:50.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:49:50.138+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:49:50.137+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:49:50.766+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:49:51.569+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:49:51.567+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:49:51.571+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:49:51.598+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:49:51.598+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:49:51.657+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.535 seconds
[2024-06-28T13:50:22.552+0000] {processor.py:161} INFO - Started process (PID=794) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:50:22.553+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:50:22.555+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:50:22.555+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:50:23.086+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:50:23.759+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:50:23.757+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:50:23.760+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:50:23.784+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:50:23.783+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:50:23.826+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.281 seconds
[2024-06-28T13:50:54.109+0000] {processor.py:161} INFO - Started process (PID=862) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:50:54.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:50:54.114+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:50:54.113+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:50:54.696+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:50:55.387+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:50:55.385+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:50:55.388+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:50:55.410+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:50:55.409+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:50:55.454+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.354 seconds
[2024-06-28T13:51:25.539+0000] {processor.py:161} INFO - Started process (PID=935) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:51:25.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:51:25.552+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:51:25.551+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:51:26.713+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:51:28.089+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:51:28.086+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:51:28.090+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:51:28.120+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:51:28.120+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:51:28.188+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 2.674 seconds
[2024-06-28T13:51:59.078+0000] {processor.py:161} INFO - Started process (PID=1009) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:51:59.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:51:59.087+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:51:59.086+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:52:00.251+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:52:01.490+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:52:01.488+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:52:01.491+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:52:01.540+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:52:01.539+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:52:01.758+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 2.697 seconds
[2024-06-28T13:52:32.049+0000] {processor.py:161} INFO - Started process (PID=1081) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:52:32.051+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:52:32.055+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:52:32.054+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:52:32.806+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:52:34.080+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:52:34.078+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:52:34.083+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:52:34.147+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:52:34.146+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:52:34.272+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 2.233 seconds
[2024-06-28T13:53:04.849+0000] {processor.py:161} INFO - Started process (PID=1162) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:53:04.851+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:53:04.855+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:53:04.854+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:53:05.794+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:53:06.898+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:53:06.897+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:53:06.900+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:53:06.928+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:53:06.927+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:53:07.126+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 2.289 seconds
[2024-06-28T13:53:37.835+0000] {processor.py:161} INFO - Started process (PID=1233) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:53:37.837+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:53:37.841+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:53:37.840+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:53:38.315+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:53:39.021+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:53:39.020+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:53:39.022+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:53:39.045+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:53:39.045+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:53:39.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.402 seconds
[2024-06-28T13:54:09.477+0000] {processor.py:161} INFO - Started process (PID=1301) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:54:09.479+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:54:09.481+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:54:09.481+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:54:09.995+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:54:10.698+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:54:10.697+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:54:10.699+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:54:10.721+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:54:10.721+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:54:10.894+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.427 seconds
[2024-06-28T13:54:40.984+0000] {processor.py:161} INFO - Started process (PID=1372) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:54:40.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:54:40.989+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:54:40.989+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:54:41.481+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:54:42.069+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:54:42.068+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:54:42.071+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:54:42.092+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:54:42.092+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:54:42.140+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.163 seconds
[2024-06-28T13:55:12.732+0000] {processor.py:161} INFO - Started process (PID=1442) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:55:12.735+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:55:12.739+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:55:12.738+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:55:13.369+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:55:14.051+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:55:14.049+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:55:14.052+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:55:14.079+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:55:14.078+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:55:14.133+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.415 seconds
[2024-06-28T13:55:44.343+0000] {processor.py:161} INFO - Started process (PID=1512) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:55:44.345+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:55:44.350+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:55:44.349+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:55:44.962+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:55:45.808+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:55:45.806+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:55:45.810+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:55:45.853+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:55:45.853+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:55:45.951+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.619 seconds
[2024-06-28T13:56:16.030+0000] {processor.py:161} INFO - Started process (PID=1583) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:56:16.032+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:56:16.034+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:56:16.034+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:56:16.547+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:56:17.304+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:56:17.303+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:56:17.306+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:56:17.331+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:56:17.331+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:56:17.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.359 seconds
[2024-06-28T13:56:48.247+0000] {processor.py:161} INFO - Started process (PID=1651) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:56:48.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:56:48.252+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:56:48.252+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:56:48.826+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:56:49.588+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:56:49.586+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:56:49.589+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:56:49.768+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:56:49.768+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:56:49.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.586 seconds
[2024-06-28T13:57:20.685+0000] {processor.py:161} INFO - Started process (PID=1720) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:57:20.687+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:57:20.690+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:57:20.690+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:57:21.223+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:57:21.895+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:57:21.894+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:57:21.896+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:57:21.920+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:57:21.920+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:57:22.105+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.429 seconds
[2024-06-28T13:57:52.316+0000] {processor.py:161} INFO - Started process (PID=1790) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:57:52.317+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:57:52.321+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:57:52.320+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:57:52.860+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:57:53.516+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:57:53.514+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:57:53.517+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:57:53.537+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:57:53.537+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:57:53.710+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.403 seconds
[2024-06-28T13:58:23.860+0000] {processor.py:161} INFO - Started process (PID=1873) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:58:23.862+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:58:23.869+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:58:23.868+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:58:24.859+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:58:26.676+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:58:26.674+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:58:26.678+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:58:26.734+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:58:26.733+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:58:26.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 2.961 seconds
[2024-06-28T13:58:57.720+0000] {processor.py:161} INFO - Started process (PID=1951) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:58:57.722+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:58:57.725+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:58:57.725+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:58:58.101+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:58:58.995+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:58:58.993+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:58:58.996+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:58:59.022+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:58:59.021+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:58:59.072+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.361 seconds
[2024-06-28T13:59:29.178+0000] {processor.py:161} INFO - Started process (PID=2026) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T13:59:29.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T13:59:29.183+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:59:29.183+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T13:59:29.555+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T13:59:30.475+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:59:30.474+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T13:59:30.476+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T13:59:30.498+0000] {logging_mixin.py:188} INFO - [2024-06-28T13:59:30.498+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T13:59:30.545+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.374 seconds
[2024-06-28T14:00:00.606+0000] {processor.py:161} INFO - Started process (PID=2102) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:00:00.608+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:00:00.612+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:00:00.611+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:00:01.054+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:00:02.045+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:00:02.043+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:00:02.046+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:00:02.077+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:00:02.076+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:00:02.132+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.533 seconds
[2024-06-28T14:00:32.208+0000] {processor.py:161} INFO - Started process (PID=2181) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:00:32.212+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:00:32.217+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:00:32.216+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:00:32.553+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:00:33.335+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:00:33.333+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:00:33.335+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:00:33.355+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:00:33.355+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:00:33.405+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.205 seconds
[2024-06-28T14:01:03.463+0000] {processor.py:161} INFO - Started process (PID=2250) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:01:03.464+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:01:03.467+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:01:03.466+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:01:03.823+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:01:04.612+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:01:04.611+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:01:04.613+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:01:04.635+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:01:04.635+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:01:04.684+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.229 seconds
[2024-06-28T14:01:35.022+0000] {processor.py:161} INFO - Started process (PID=2318) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:01:35.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:01:35.027+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:01:35.027+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:01:35.361+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:01:36.188+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:01:36.186+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:01:36.189+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:01:36.210+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:01:36.210+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:01:36.256+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.241 seconds
[2024-06-28T14:02:06.537+0000] {processor.py:161} INFO - Started process (PID=2386) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:02:06.538+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:02:06.541+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:02:06.541+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:02:06.878+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:02:07.690+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:02:07.689+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:02:07.691+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:02:07.713+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:02:07.713+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:02:07.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.232 seconds
[2024-06-28T14:02:37.854+0000] {processor.py:161} INFO - Started process (PID=2458) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:02:37.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:02:37.859+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:02:37.859+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:02:38.180+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:02:38.985+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:02:38.984+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:02:38.987+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:02:39.009+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:02:39.008+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:02:39.055+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.209 seconds
[2024-06-28T14:03:09.122+0000] {processor.py:161} INFO - Started process (PID=2526) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:03:09.124+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:03:09.127+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:03:09.126+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:03:09.447+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:03:10.248+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:03:10.247+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:03:10.249+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:03:10.274+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:03:10.274+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:03:10.322+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.209 seconds
[2024-06-28T14:03:40.532+0000] {processor.py:161} INFO - Started process (PID=2613) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:03:40.534+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:03:40.539+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:03:40.539+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:03:41.305+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:03:42.830+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:03:42.828+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:03:42.832+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:03:42.885+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:03:42.885+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:03:42.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 2.456 seconds
[2024-06-28T14:04:13.936+0000] {processor.py:161} INFO - Started process (PID=2681) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:04:13.938+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:04:13.943+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:04:13.942+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:04:14.612+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:04:15.845+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:04:15.843+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:04:15.846+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:04:15.875+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:04:15.875+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:04:15.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 2.004 seconds
[2024-06-28T14:04:46.448+0000] {processor.py:161} INFO - Started process (PID=2749) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:04:46.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:04:46.458+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:04:46.457+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:04:47.009+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:04:48.110+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:04:48.108+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:04:48.111+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:04:48.138+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:04:48.137+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:04:48.186+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.756 seconds
[2024-06-28T14:05:18.988+0000] {processor.py:161} INFO - Started process (PID=2818) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:05:18.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:05:18.994+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:05:18.994+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:05:19.384+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:05:20.224+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:05:20.223+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:05:20.225+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:05:20.249+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:05:20.248+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:05:20.298+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.324 seconds
[2024-06-28T14:05:50.491+0000] {processor.py:161} INFO - Started process (PID=2888) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:05:50.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:05:50.497+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:05:50.496+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:05:50.897+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:05:51.726+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:05:51.724+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:05:51.727+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:05:51.752+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:05:51.751+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:05:51.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.323 seconds
[2024-06-28T14:06:21.868+0000] {processor.py:161} INFO - Started process (PID=2957) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:06:21.870+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:06:21.872+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:06:21.872+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:06:22.231+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:06:23.100+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:06:23.099+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:06:23.102+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:06:23.126+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:06:23.126+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:06:23.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.316 seconds
[2024-06-28T14:06:53.822+0000] {processor.py:161} INFO - Started process (PID=3031) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:06:53.824+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:06:53.827+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:06:53.827+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:06:54.247+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:06:55.147+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:06:55.145+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:06:55.148+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:06:55.172+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:06:55.171+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:06:55.219+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.404 seconds
[2024-06-28T14:07:25.370+0000] {processor.py:161} INFO - Started process (PID=3102) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:07:25.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:07:25.374+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:07:25.373+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:07:25.741+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:07:26.551+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:07:26.550+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:07:26.553+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:07:26.577+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:07:26.577+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:07:26.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.258 seconds
[2024-06-28T14:07:56.788+0000] {processor.py:161} INFO - Started process (PID=3174) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:07:56.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:07:56.793+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:07:56.792+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:07:57.128+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:07:57.976+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:07:57.975+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:07:57.977+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:07:57.998+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:07:57.998+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:07:58.040+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.260 seconds
[2024-06-28T14:08:28.139+0000] {processor.py:161} INFO - Started process (PID=3248) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:08:28.140+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:08:28.142+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:08:28.142+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:08:28.484+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:08:29.312+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:08:29.311+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:08:29.313+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:08:29.336+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:08:29.335+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:08:29.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.255 seconds
[2024-06-28T14:08:59.735+0000] {processor.py:161} INFO - Started process (PID=3334) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:08:59.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:08:59.744+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:08:59.743+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:09:00.482+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:09:02.254+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:09:02.252+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:09:02.256+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:09:02.301+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:09:02.300+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:09:02.409+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 2.688 seconds
[2024-06-28T14:09:33.241+0000] {processor.py:161} INFO - Started process (PID=3404) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:09:33.243+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:09:33.246+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:09:33.245+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:09:33.696+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:09:34.870+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:09:34.868+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:09:34.872+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:09:34.906+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:09:34.905+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:09:34.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.748 seconds
[2024-06-28T14:10:05.590+0000] {processor.py:161} INFO - Started process (PID=3474) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:10:05.592+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:10:05.595+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:10:05.594+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:10:06.025+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:10:06.884+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:10:06.883+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:10:06.885+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:10:06.907+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:10:06.907+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:10:06.954+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.373 seconds
[2024-06-28T14:10:48.284+0000] {processor.py:161} INFO - Started process (PID=3531) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:10:48.285+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:10:48.288+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:10:48.288+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:10:48.686+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:10:49.590+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:10:49.589+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:10:49.592+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:10:49.615+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:10:49.615+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:10:49.667+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.391 seconds
[2024-06-28T14:11:19.741+0000] {processor.py:161} INFO - Started process (PID=3612) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:11:19.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:11:19.746+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:11:19.745+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:11:20.490+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:11:21.583+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:11:21.581+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:11:21.585+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:11:21.620+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:11:21.619+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:11:21.676+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.946 seconds
[2024-06-28T14:11:52.143+0000] {processor.py:161} INFO - Started process (PID=3685) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:11:52.144+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:11:52.147+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:11:52.147+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:11:52.591+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:11:53.703+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:11:53.701+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:11:53.704+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:11:53.731+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:11:53.730+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:11:53.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.656 seconds
[2024-06-28T14:12:24.401+0000] {processor.py:161} INFO - Started process (PID=3758) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:12:24.403+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:12:24.406+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:12:24.405+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:12:24.832+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:12:25.746+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:12:25.745+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:12:25.747+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:12:25.770+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:12:25.770+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:12:25.828+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.436 seconds
[2024-06-28T14:12:55.970+0000] {processor.py:161} INFO - Started process (PID=3834) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:12:55.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:12:55.974+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:12:55.974+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:12:56.340+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:12:57.260+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:12:57.259+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:12:57.262+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:12:57.287+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:12:57.286+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:12:57.335+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.372 seconds
[2024-06-28T14:13:27.476+0000] {processor.py:161} INFO - Started process (PID=3910) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:13:27.478+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:13:27.481+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:13:27.481+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:13:27.871+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:13:28.840+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:13:28.837+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:13:28.841+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:13:28.866+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:13:28.865+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:13:28.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.458 seconds
[2024-06-28T14:13:59.279+0000] {processor.py:161} INFO - Started process (PID=3988) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:13:59.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:13:59.285+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:13:59.285+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:13:59.663+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:14:00.449+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:14:00.448+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:14:00.449+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:14:00.470+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:14:00.470+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:14:00.513+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.243 seconds
[2024-06-28T14:14:35.082+0000] {processor.py:161} INFO - Started process (PID=4068) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:14:35.090+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:14:35.104+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:14:35.102+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:14:47.145+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:14:49.073+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:14:49.071+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:14:49.075+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:14:49.113+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:14:49.113+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:14:49.197+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 14.158 seconds
[2024-06-28T14:15:22.176+0000] {processor.py:161} INFO - Started process (PID=4138) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:15:22.179+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:15:22.183+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:15:22.183+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:15:22.540+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:15:21.540+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:15:21.537+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:15:21.542+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:15:21.706+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:15:21.695+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:15:21.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 5.691 seconds
[2024-06-28T14:15:52.088+0000] {processor.py:161} INFO - Started process (PID=4207) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:15:52.090+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:15:52.092+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:15:52.092+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:15:52.588+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:15:53.626+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:15:53.624+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:15:53.627+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:15:53.661+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:15:53.660+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:15:53.727+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.648 seconds
[2024-06-28T14:16:24.300+0000] {processor.py:161} INFO - Started process (PID=4292) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:16:24.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:16:24.305+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:16:24.304+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:16:24.638+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:16:25.563+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:16:25.561+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:16:25.565+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:16:25.593+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:16:25.593+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:16:25.643+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.350 seconds
[2024-06-28T14:16:55.975+0000] {processor.py:161} INFO - Started process (PID=4363) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:16:55.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:16:55.979+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:16:55.979+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:16:56.416+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:16:57.367+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:16:57.365+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:16:57.368+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:16:57.395+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:16:57.395+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:16:57.448+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.484 seconds
[2024-06-28T14:17:28.346+0000] {processor.py:161} INFO - Started process (PID=4437) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:17:28.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:17:28.351+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:17:28.350+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:17:28.769+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:17:29.602+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:17:29.601+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:17:29.603+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:17:29.626+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:17:29.626+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:17:29.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.334 seconds
[2024-06-28T14:18:00.124+0000] {processor.py:161} INFO - Started process (PID=4512) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:18:00.126+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:18:00.129+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:18:00.128+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:18:00.489+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:18:01.355+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:18:01.353+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:18:01.356+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:18:01.378+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:18:01.378+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:18:01.423+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.307 seconds
[2024-06-28T14:18:31.576+0000] {processor.py:161} INFO - Started process (PID=4583) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:18:31.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:18:31.581+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:18:31.580+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:18:31.949+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:18:32.827+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:18:32.825+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:18:32.828+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:18:32.853+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:18:32.852+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:18:32.914+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.345 seconds
[2024-06-28T14:19:02.972+0000] {processor.py:161} INFO - Started process (PID=4651) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:19:02.973+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:19:02.977+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:19:02.976+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:19:03.399+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:19:04.379+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:19:04.378+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:19:04.380+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:19:04.402+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:19:04.402+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:19:04.451+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.490 seconds
[2024-06-28T14:19:34.825+0000] {processor.py:161} INFO - Started process (PID=4735) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:19:34.837+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:19:34.861+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:19:34.849+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:19:35.814+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:19:37.830+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:19:37.828+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:19:37.841+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:19:37.920+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:19:37.920+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:19:38.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 3.221 seconds
[2024-06-28T14:20:09.027+0000] {processor.py:161} INFO - Started process (PID=4812) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:20:09.028+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:20:09.032+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:20:09.031+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:20:09.698+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:20:10.578+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:20:10.576+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:20:10.581+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:20:10.615+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:20:10.615+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:20:10.680+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.663 seconds
[2024-06-28T14:20:40.852+0000] {processor.py:161} INFO - Started process (PID=4886) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:20:40.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:20:40.857+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:20:40.857+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:20:41.243+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:20:42.105+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:20:42.104+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:20:42.106+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:20:42.125+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:20:42.125+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:20:42.166+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.322 seconds
[2024-06-28T14:21:12.578+0000] {processor.py:161} INFO - Started process (PID=4958) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:21:12.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:21:12.583+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:21:12.582+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:21:13.192+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:21:13.979+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:21:13.978+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:21:13.980+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:21:14.002+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:21:14.002+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:21:14.052+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.484 seconds
[2024-06-28T14:21:44.154+0000] {processor.py:161} INFO - Started process (PID=5029) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:21:44.160+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:21:44.164+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:21:44.164+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:21:44.549+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:21:45.347+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:21:45.346+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:21:45.349+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:21:45.378+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:21:45.378+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:21:45.427+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.283 seconds
[2024-06-28T14:22:15.758+0000] {processor.py:161} INFO - Started process (PID=5098) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:22:15.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:22:15.763+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:22:15.762+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:22:16.140+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:22:16.963+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:22:16.962+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:22:16.965+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:22:16.987+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:22:16.986+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:22:17.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.282 seconds
[2024-06-28T14:22:47.879+0000] {processor.py:161} INFO - Started process (PID=5166) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:22:47.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:22:47.883+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:22:47.883+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:22:48.269+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:22:49.150+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:22:49.148+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:22:49.151+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:22:49.172+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:22:49.171+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:22:49.216+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.346 seconds
[2024-06-28T14:23:19.340+0000] {processor.py:161} INFO - Started process (PID=5238) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:23:19.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:23:19.345+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:23:19.344+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:23:19.877+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:23:20.539+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:23:20.538+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:23:20.540+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:23:20.564+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:23:20.563+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:23:20.607+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.274 seconds
[2024-06-28T14:23:50.655+0000] {processor.py:161} INFO - Started process (PID=5306) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:23:50.657+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:23:50.661+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:23:50.661+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:23:51.209+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:23:51.835+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:23:51.834+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:23:51.837+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:23:51.862+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:23:51.862+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:23:51.917+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.270 seconds
[2024-06-28T14:24:22.736+0000] {processor.py:161} INFO - Started process (PID=5374) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:24:22.738+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:24:22.743+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:24:22.742+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:24:23.302+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:24:24.091+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:24:24.069+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:24:24.095+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:24:24.120+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:24:24.120+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:24:24.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.445 seconds
[2024-06-28T14:24:54.252+0000] {processor.py:161} INFO - Started process (PID=5451) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:24:54.254+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:24:54.257+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:24:54.257+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:24:55.041+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:24:56.305+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:24:56.303+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:24:56.307+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:24:56.348+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:24:56.348+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:24:56.435+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 2.193 seconds
[2024-06-28T14:25:27.164+0000] {processor.py:161} INFO - Started process (PID=5533) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:25:27.165+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:25:27.168+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:25:27.167+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:25:27.663+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:25:28.333+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:25:28.332+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:25:28.334+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:25:28.356+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:25:28.356+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:25:28.383+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:25:28.383+0000] {dag.py:3954} INFO - Setting next_dagrun for my_sample_dag to 2023-08-16 07:20:00+00:00, run_after=2023-08-16 07:25:00+00:00
[2024-06-28T14:25:28.405+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.252 seconds
[2024-06-28T14:25:58.524+0000] {processor.py:161} INFO - Started process (PID=5600) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:25:58.526+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:25:58.529+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:25:58.529+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:25:59.132+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:25:59.867+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:25:59.865+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:25:59.868+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:25:59.893+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:25:59.892+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:25:59.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.425 seconds
[2024-06-28T14:26:22.845+0000] {processor.py:161} INFO - Started process (PID=5661) to work on /opt/airflow/dags/my_dag.py
[2024-06-28T14:26:22.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-06-28T14:26:22.849+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:26:22.849+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-06-28T14:26:23.473+0000] {logging_mixin.py:188} INFO -   ok..
[2024-06-28T14:26:25.015+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:26:25.012+0000] {templater.py:93} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 91, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T14:26:25.016+0000] {processor.py:840} INFO - DAG(s) 'my_sample_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-06-28T14:26:25.067+0000] {logging_mixin.py:188} INFO - [2024-06-28T14:26:25.067+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-28T14:26:25.157+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 2.323 seconds
