[2024-06-28T14:03:41.971+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T14:03:42.037+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_sample_dag.task_from_script1 scheduled__2023-08-16T02:50:00+00:00 [queued]>
[2024-06-28T14:03:42.065+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_sample_dag.task_from_script1 scheduled__2023-08-16T02:50:00+00:00 [queued]>
[2024-06-28T14:03:42.074+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T14:03:42.123+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task_from_script1> on 2023-08-16 02:50:00+00:00
[2024-06-28T14:03:42.163+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_sample_dag', 'task_from_script1', 'scheduled__2023-08-16T02:50:00+00:00', '--job-id', '1823', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp23w7cxzr']
[2024-06-28T14:03:42.176+0000] {standard_task_runner.py:91} INFO - Job 1823: Subtask task_from_script1
[2024-06-28T14:03:42.158+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1567) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T14:03:42.183+0000] {standard_task_runner.py:63} INFO - Started process 1657 to run task
[2024-06-28T14:03:42.400+0000] {task_command.py:426} INFO - Running <TaskInstance: my_sample_dag.task_from_script1 scheduled__2023-08-16T02:50:00+00:00 [running]> on host 81089ac3a69d
[2024-06-28T14:03:42.868+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_sample_dag' AIRFLOW_CTX_TASK_ID='task_from_script1' AIRFLOW_CTX_EXECUTION_DATE='2023-08-16T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-16T02:50:00+00:00'
[2024-06-28T14:03:42.876+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T14:03:42.877+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T14:03:42.883+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/script1.py", line 10, in function_from_script1
    response = requests.get(url)
                            ^^^
NameError: name 'url' is not defined
[2024-06-28T14:03:42.918+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=my_sample_dag, task_id=task_from_script1, run_id=scheduled__2023-08-16T02:50:00+00:00, execution_date=20230816T025000, start_date=20240628T140342, end_date=20240628T140342
[2024-06-28T14:03:42.974+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1823 for task task_from_script1 (name 'url' is not defined; 1657)
[2024-06-28T14:03:43.047+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T14:03:43.084+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
